try {
    console.log(a)
    throw new reference="hello"
} catch (error) {
    // console.log(error)
    console.log(error)
}